language: python

os:
  - "linux"
  - "osx"
  
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install requests
  - pip install python-coveralls

script: 
  - coverage run --source='.' YaDiskClient/TestYaDisk.py
after_success:
  - coveralls