language: python

os:
  - "linux"
  
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install requests
  - pip install python-coveralls

script: 
  - coverage run -m unittest discover -s tests -t tests
after_success:
  - coveralls